

version: "3.4"

volumes:
  db-data:
  logs:

services:
  mysql:
    container_name: prueba
    image: "mariadb:latest"
    environment:
      MYSQL_ROOT_PASSWORD: trinity
      MYSQL_USER: trinity
      MYSQL_PASSWORD: trinity
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      timeout: 20s
      retries: 10
      start_period: 20s
    ports:
    - "3306:3306"
    volumes:
    - db-data:/var/lib/mysql
    - ./sql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

